import AuthComponent from '../modules/portal/src/authenticated_component.js';
import SessionList from '../modules/portal/src/session_list.js';
import { Menu } from '../template/components.js';
const Index = () => (
        <Menu marquee={true}>
            <div>
            
                <SessionList />
                <AuthComponent site="stackoverflow">Welcome</AuthComponent>
                <div className="page-generator__output js-generator-output" id="output"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac turpis egestas sed tempus urna et pharetra. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Nunc sed blandit libero volutpat sed cras ornare. Aenean et tortor at risus viverra. Placerat vestibulum lectus mauris ultrices eros in. Ac ut consequat semper viverra nam libero justo laoreet sit. Morbi tristique senectus et netus et malesuada fames ac turpis. Nulla facilisi morbi tempus iaculis urna id. A diam maecenas sed enim ut sem viverra aliquet. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Scelerisque in dictum non consectetur. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Nulla pellentesque dignissim enim sit.</p>
    <p>Nullam eget felis eget nunc. Commodo ullamcorper a lacus vestibulum sed. Fames ac turpis egestas sed tempus urna et. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Egestas integer eget aliquet nibh praesent tristique. Pretium viverra suspendisse potenti nullam. Aliquam faucibus purus in massa. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Sit amet nisl purus in mollis. Nisi porta lorem mollis aliquam ut porttitor leo. Morbi tincidunt augue interdum velit euismod. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Aenean sed adipiscing diam donec adipiscing tristique risus. In fermentum posuere urna nec tincidunt praesent. Sit amet nulla facilisi morbi tempus iaculis urna id. Egestas dui id ornare arcu odio ut sem nulla.</p>
    <p>Viverra orci sagittis eu volutpat odio facilisis mauris sit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Integer quis auctor elit sed vulputate mi. Bibendum neque egestas congue quisque. Amet volutpat consequat mauris nunc. Dui vivamus arcu felis bibendum ut tristique et. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Fermentum odio eu feugiat pretium nibh ipsum. Habitant morbi tristique senectus et netus et malesuada. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Aliquet sagittis id consectetur purus. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Est pellentesque elit ullamcorper dignissim cras tincidunt. Rhoncus aenean vel elit scelerisque.</p>
    <p>Enim sit amet venenatis urna cursus. Lectus arcu bibendum at varius. Aenean sed adipiscing diam donec. Suspendisse sed nisi lacus sed viverra tellus in. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Dictum non consectetur a erat nam. Ut enim blandit volutpat maecenas volutpat. Ornare lectus sit amet est. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu.</p>
    <p>Netus et malesuada fames ac turpis egestas. Mattis nunc sed blandit libero volutpat sed. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Morbi tincidunt ornare massa eget. Ipsum nunc aliquet bibendum enim facilisis gravida. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Aliquet enim tortor at auctor. Volutpat odio facilisis mauris sit amet. Sed id semper risus in. Nunc aliquet bibendum enim facilisis.</p></div>
    <div className="page-generator__output js-generator-output" id="output"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac turpis egestas sed tempus urna et pharetra. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Nunc sed blandit libero volutpat sed cras ornare. Aenean et tortor at risus viverra. Placerat vestibulum lectus mauris ultrices eros in. Ac ut consequat semper viverra nam libero justo laoreet sit. Morbi tristique senectus et netus et malesuada fames ac turpis. Nulla facilisi morbi tempus iaculis urna id. A diam maecenas sed enim ut sem viverra aliquet. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Scelerisque in dictum non consectetur. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Nulla pellentesque dignissim enim sit.</p>
    <p>Nullam eget felis eget nunc. Commodo ullamcorper a lacus vestibulum sed. Fames ac turpis egestas sed tempus urna et. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Egestas integer eget aliquet nibh praesent tristique. Pretium viverra suspendisse potenti nullam. Aliquam faucibus purus in massa. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Sit amet nisl purus in mollis. Nisi porta lorem mollis aliquam ut porttitor leo. Morbi tincidunt augue interdum velit euismod. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Aenean sed adipiscing diam donec adipiscing tristique risus. In fermentum posuere urna nec tincidunt praesent. Sit amet nulla facilisi morbi tempus iaculis urna id. Egestas dui id ornare arcu odio ut sem nulla.</p>
    <p>Viverra orci sagittis eu volutpat odio facilisis mauris sit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Integer quis auctor elit sed vulputate mi. Bibendum neque egestas congue quisque. Amet volutpat consequat mauris nunc. Dui vivamus arcu felis bibendum ut tristique et. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Fermentum odio eu feugiat pretium nibh ipsum. Habitant morbi tristique senectus et netus et malesuada. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Aliquet sagittis id consectetur purus. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Est pellentesque elit ullamcorper dignissim cras tincidunt. Rhoncus aenean vel elit scelerisque.</p>
    <p>Enim sit amet venenatis urna cursus. Lectus arcu bibendum at varius. Aenean sed adipiscing diam donec. Suspendisse sed nisi lacus sed viverra tellus in. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Dictum non consectetur a erat nam. Ut enim blandit volutpat maecenas volutpat. Ornare lectus sit amet est. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu.</p>
    <p>Netus et malesuada fames ac turpis egestas. Mattis nunc sed blandit libero volutpat sed. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Morbi tincidunt ornare massa eget. Ipsum nunc aliquet bibendum enim facilisis gravida. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Aliquet enim tortor at auctor. Volutpat odio facilisis mauris sit amet. Sed id semper risus in. Nunc aliquet bibendum enim facilisis.</p></div>
    <div className="page-generator__output js-generator-output" id="output"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac turpis egestas sed tempus urna et pharetra. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Nunc sed blandit libero volutpat sed cras ornare. Aenean et tortor at risus viverra. Placerat vestibulum lectus mauris ultrices eros in. Ac ut consequat semper viverra nam libero justo laoreet sit. Morbi tristique senectus et netus et malesuada fames ac turpis. Nulla facilisi morbi tempus iaculis urna id. A diam maecenas sed enim ut sem viverra aliquet. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Scelerisque in dictum non consectetur. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Nulla pellentesque dignissim enim sit.</p>
    <p>Nullam eget felis eget nunc. Commodo ullamcorper a lacus vestibulum sed. Fames ac turpis egestas sed tempus urna et. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Egestas integer eget aliquet nibh praesent tristique. Pretium viverra suspendisse potenti nullam. Aliquam faucibus purus in massa. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Sit amet nisl purus in mollis. Nisi porta lorem mollis aliquam ut porttitor leo. Morbi tincidunt augue interdum velit euismod. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Aenean sed adipiscing diam donec adipiscing tristique risus. In fermentum posuere urna nec tincidunt praesent. Sit amet nulla facilisi morbi tempus iaculis urna id. Egestas dui id ornare arcu odio ut sem nulla.</p>
    <p>Viverra orci sagittis eu volutpat odio facilisis mauris sit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Integer quis auctor elit sed vulputate mi. Bibendum neque egestas congue quisque. Amet volutpat consequat mauris nunc. Dui vivamus arcu felis bibendum ut tristique et. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Fermentum odio eu feugiat pretium nibh ipsum. Habitant morbi tristique senectus et netus et malesuada. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Aliquet sagittis id consectetur purus. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Est pellentesque elit ullamcorper dignissim cras tincidunt. Rhoncus aenean vel elit scelerisque.</p>
    <p>Enim sit amet venenatis urna cursus. Lectus arcu bibendum at varius. Aenean sed adipiscing diam donec. Suspendisse sed nisi lacus sed viverra tellus in. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Dictum non consectetur a erat nam. Ut enim blandit volutpat maecenas volutpat. Ornare lectus sit amet est. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu.</p>
    <p>Netus et malesuada fames ac turpis egestas. Mattis nunc sed blandit libero volutpat sed. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Morbi tincidunt ornare massa eget. Ipsum nunc aliquet bibendum enim facilisis gravida. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Aliquet enim tortor at auctor. Volutpat odio facilisis mauris sit amet. Sed id semper risus in. Nunc aliquet bibendum enim facilisis.</p></div>
            </div>
        </Menu>
  );
  
  export default Index;